[package]
name = "meeters"
version = "0.1.0"
authors = ["Boris Terzic <boris@terzic.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libappindicator = "0.5.2"
gtk = "0.9.2"
glib = "0.10.3"
ureq = "1.5.2"
ical = "0.7.0"
property = "0.3.3"
chrono = "0.4.19"
chrono-tz = "0.5.3"
rrule = "0.3.8"
regex ="1"
lazy_static = "1.4.0"
directories = "3.0.1"
dotenv = "0.15.0"
maplit = "1.0.2"
roxmltree = "0.14.0"
notify-rust = "4"
