on:
  release:
    types: [created]

name: Create and Upload Release Artifact

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install Linux build deps
        run: sudo apt install libdbus-1-dev libgtk-3-dev libappindicator3-dev          
      - name: Build and Package Release
        run: |
          cargo build --release
          cp assets/* target/release/
          tar -zcf meeters-${{ steps.get_version.outputs.VERSION }}-linux-x86.tar.gz -C target/release meeters *.png
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'meeters-*'
